const SQUARE_SIZE = 12;
const DAY_LABEL_GUTTER_SIZE = 8;
const MILLISECONDS_IN_ONE_DAY = 24 * 60 * 60 * 1000;
const HOURS_IN_DAY = 24;

export {
  SQUARE_SIZE,
  HOURS_IN_DAY,
  DAY_LABEL_GUTTER_SIZE,
  MILLISECONDS_IN_ONE_DAY
};
export default {
  SQUARE_SIZE,
  HOURS_IN_DAY,
  DAY_LABEL_GUTTER_SIZE,
  MILLISECONDS_IN_ONE_DAY
};
